openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/streetzy/TODO/1.0.0
info:
  description: API for TODO app
  version: "1.0.0"
  title: TODO
  contact:
    email: sindler.ad.2021@skola.ssps.cz
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: owner
    description: Operations only available to owner of group
  - name: member
    description: Operations only available to members of group
  - name: user
    description: Operations only available to a user that isn't in a group
paths: 
  /register:
    post:
      summary: create a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: user registered
        '401':
          description: registration failed
  /login:
    post:
      summary: create a refresh & access token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: token generated
        '404':
          description: user not found
    delete:
      summary: remove refresh token from database
      responses:
        '200':
          description: OK
        '404':
          description: user not found
  
components:
  schemas:
    User:
      type: object
      required:
        - username
        - email
        - password
        - groups
        - inviteList