POST http://localhost:3000/user
Content-Type: application/json

{
    "email":"addam.mimrix@miimrix.com",
    "password":"asdasdojsdfgjdfgnjl"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"addam.mimrix@miimrix.com",
    "password":"asdasdojsdfgjdfgnjl"
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjUyMDFhYzRkZTcyNWUwMGJiYjg2MSIsImlhdCI6MTcxMzcwOTUyN30.bteYmoDP6aZ_M2PxjIaTxHYV9gGoFKuctntwlxblwRY"   
}

###
POST http://localhost:3000/group
Content-Type: application/json
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjUyMDFhYzRkZTcyNWUwMGJiYjg2MSIsImlhdCI6MTcxNzA5NDA2NSwiZXhwIjoxNzE3MDk0NjY1fQ.S6PpnHygZ0wWUTNkJBXO96ydgjeqnBx5FHX9rvd6P2Y

{
    
    "groupName":"addam.mimrix@mimrix.com"

}

###
GET http://localhost:3000/group/662537099cb1dc75c1a82961
Content-Type: application/json
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjUyMDFhYzRkZTcyNWUwMGJiYjg2MSIsImlhdCI6MTcxMzcxOTQ4NCwiZXhwIjoxNzEzNzIwMDg0fQ.5QbMPTzTZFb6uPdBBwJgxMqNc1_CS4RdlA0cysPJ2lY



###
PATCH http://localhost:3000/group/662537099cb1dc75c1a82961
Content-Type: application/json
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjUyMDFhYzRkZTcyNWUwMGJiYjg2MSIsImlhdCI6MTcxNzA5NDA2NSwiZXhwIjoxNzE3MDk0NjY1fQ.S6PpnHygZ0wWUTNkJBXO96ydgjeqnBx5FHX9rvd6P2Y

{
    "groupName":"fdgdfgdfgdfgg"
}

###

POST http://localhost:3000/group/662537099cb1dc75c1a82961/invite
Content-Type: application/json
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjUyMDFhYzRkZTcyNWUwMGJiYjg2MSIsImlhdCI6MTcxNzA4MTY0MCwiZXhwIjoxNzE3MDgyMjQwfQ.e7HTYURfK5loRcdvvwdvRXQz09WGcpcWEwh7hJNRyQ0
{
    "userId":" "
}

###
POST http://localhost:3000/user/invite/
Content-Type: application/json
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MjUyMDFhYzRkZTcyNWUwMGJiYjg2MSIsImlhdCI6MTcxNzA4MTY0MCwiZXhwIjoxNzE3MDgyMjQwfQ.e7HTYURfK5loRcdvvwdvRXQz09WGcpcWEwh7hJNRyQ0

###
